# src/ai/web_learning/config/domain_config.py

TRUSTED_DOMAINS = {
    'educational': [
        'edu',
        'ac.uk',
        'edu.au',
        'ac.jp',
        'edu.cn',
        'ac.ir',
        'edu.in',
        'ac.nz',
        'edu.sg',
        'ac.kr',
        'edu.br',
        'edu.mx',
        'ac.za'
    ],
    
    'scientific': [
        'arxiv.org',
        'science.org',
        'nature.com',
        'scholar.google.com',
        'sciencedirect.com',
        'ieee.org',
        'researchgate.net',
        'springer.com',
        'wiley.com',
        'acm.org',
        'cell.com',
        'pnas.org',
        'aps.org',
        'acs.org',
        'pubmed.ncbi.nlm.nih.gov',
        'webofscience.com',
        'biomedcentral.com',
        'frontiersin.org',
        'scientificamerican.com',
        'science.nasa.gov',
        'sciencemag.org'
    ],
    
    'documentation': [
        'docs.python.org',
        'tensorflow.org',
        'pytorch.org',
        'kubernetes.io',
        'docker.com',
        'aws.amazon.com/documentation',
        'docs.microsoft.com',
        'cloud.google.com/docs',
        'developer.mozilla.org',
        'reactjs.org',
        'vuejs.org',
        'angular.io',
        'docs.oracle.com',
        'postgresql.org/docs',
        'mysql.com/doc',
        'mongodb.com/docs',
        'redis.io/documentation',
        'elasticsearch.co/guide',
        'nginx.org/en/docs',
        'apache.org/docs',
        'jenkins.io/doc',
        'gitlab.com/help',
        'rust-lang.org/learn',
        'go.dev/doc',
        'docs.djangoproject.com',
        'flask.palletsprojects.com',
        'laravel.com/docs',
        'ruby-doc.org'
    ],
    
    'community': [
        'stackoverflow.com',
        'github.com',
        'dev.to',
        'medium.com',
        'hashnode.com',
        'reddit.com/r/programming',
        'reddit.com/r/learnprogramming',
        'reddit.com/r/coding',
        'reddit.com/r/webdev',
        'reddit.com/r/MachineLearning',
        'reddit.com/r/datascience',
        'reddit.com/r/artificial',
        'reddit.com/r/computerscience',
        'hackernews.com',
        'lobste.rs',
        'codepen.io',
        'jsfiddle.net',
        'replit.com',
        'kaggle.com',
        'towardsdatascience.com',
        'freecodecamp.org',
        'codecademy.com',
        'w3schools.com',
        'geeksforgeeks.org',
        'tutorialspoint.com'
    ],
    
    'tech_blogs': [
        'techcrunch.com',
        'wired.com',
        'arstechnica.com',
        'thenextweb.com',
        'venturebeat.com',
        'zdnet.com',
        'infoworld.com',
        'computerworld.com',
        'cnet.com/tech',
        'engineering.facebook.com',
        'developers.googleblog.com',
        'aws.amazon.com/blogs/aws',
        'blogs.microsoft.com',
        'netflix.github.io',
        'instagram-engineering.com',
        'slack.engineering',
        'blog.twitter.com/engineering',
        'blog.discord.com',
        'spotify.engineering',
        'uber.com/blog/engineering'
    ],
    
    'research_institutes': [
        'mit.edu',
        'stanford.edu',
        'harvard.edu',
        'berkeley.edu',
        'cam.ac.uk',
        'ox.ac.uk',
        'caltech.edu',
        'cern.ch',
        'nih.gov',
        'nasa.gov',
        'research.ibm.com',
        'research.google',
        'research.microsoft.com',
        'research.facebook.com',
        'deepmind.com',
        'openai.com',
        'anthropic.com',
        'baidu.com/research',
        'labs.yahoo.com',
        'research.nvidia.com'
    ]
}

# Optional scoring weights for different domain categories
DOMAIN_WEIGHTS = {
    'educational': 0.9,
    'scientific': 0.85,
    'research_institutes': 0.8,
    'documentation': 0.75,
    'community': 0.6,
    'tech_blogs': 0.5
}